### ISSUE TITLE
Works when phpcs is installed in project but not globally in docker

### ISSUE THREAD

**Issue by cballenar** [mtbdata711/vscode-phpsab-docker#16]
I was able to get the plugin running when installed in the project, (i.e., `./vendor/bin/phpcs`) but the same setup fails if I try to run it from phpcs being globally installed in docker (i.e., `/usr/local/bin/phpcs`).

### Problems Observed
- PHPCS issues don't come up in the Problems tab
- When trying to use PHPCBF, it never finishes loading
- When trying to use phpsab.docker to format a file, I get the message "Fixer is disable for this workspace or PHPCBF was not found for this workspace."

It's also worth noting that I'm able to see errors reported by PHPCS using the same configuration in phpsab within the VM, (by using "Attach to running container").

Could the issue be related to these libraries being installed globally outside of composer? 

Is there a way I could troubleshoot or see more information about the error or what's causing it?

**Comment by cballenar** [comment]
I just figured out where the debug logs go. Strangely, it first reports docker resolved the path but then immediately after it says the executable was not found:

```
["INFO" - 5:58:03 PM] DOCKER: Resolved docker path: /usr/local/bin/phpcbf
["INFO" - 5:58:03 PM] DOCKER: Resolved docker path: /usr/local/bin/phpcs
["INFO" - 5:58:03 PM] The phpcs executable was not found for sandbox
["INFO" - 5:58:03 PM] The phpcbf executable was not found for sandbox
["INFO" - 5:58:03 PM] VALIDATED
{
  "useFilepath": false,
  "containerExec": "docker",
  "fixerEnable": false,
  "fixerArguments": [],
  "workspaceRoot": "/Users/cballenar/Repositories/sandbox/sandbox",
  "executablePathCBF": "/usr/local/bin/phpcbf",
  "executablePathCS": "/usr/local/bin/phpcs",
  "composerJsonPath": "composer.json",
  "standard": null,
  "autoRulesetSearch": true,
  "allowedAutoRulesets": [
    ".phpcs.xml",
    ".phpcs.xml.dist",
    "phpcs.xml",
    "phpcs.xml.dist",
    "phpcs.ruleset.xml",
    "ruleset.xml"
  ],
  "snifferEnable": false,
  "snifferArguments": [],
  "dockerEnabled": true,
  "dockerContainer": "ddev-sandbox-web",
  "dockerWorkspaceRoot": "/var/www/html/docroot/",
  "dockerExecutablePathCBF": "/usr/local/bin/phpcbf",
  "dockerExecutablePathCS": "/usr/local/bin/phpcs"
}
["INFO" - 5:58:03 PM] CONFIGURATION
{
  "resources": [
    {
      "useFilepath": false,
      "containerExec": "docker",
      "fixerEnable": false,
      "fixerArguments": [],
      "workspaceRoot": "/Users/cballenar/Repositories/sandbox/sandbox",
      "executablePathCBF": "/usr/local/bin/phpcbf",
      "executablePathCS": "/usr/local/bin/phpcs",
      "composerJsonPath": "composer.json",
      "standard": null,
      "autoRulesetSearch": true,
      "allowedAutoRulesets": [
        ".phpcs.xml",
        ".phpcs.xml.dist",
        "phpcs.xml",
        "phpcs.xml.dist",
        "phpcs.ruleset.xml",
        "ruleset.xml"
      ],
      "snifferEnable": false,
      "snifferArguments": [],
      "dockerEnabled": true,
      "dockerContainer": "ddev-sandbox-web",
      "dockerWorkspaceRoot": "/var/www/html/docroot/",
      "dockerExecutablePathCBF": "/usr/local/bin/phpcbf",
      "dockerExecutablePathCS": "/usr/local/bin/phpcs"
    }
  ],
  "snifferMode": "onSave",
  "snifferShowSources": false,
  "snifferTypeDelay": 250,
  "debug": true
}
```

**Comment by mtbdata711** [comment]
Hey Carlos!

This is a confusing one.

I've just given this a test locally and I was able to get this to work on my system.

Please see an example configuration below:

```
{
	"phpsab.docker.dockerEnabled": true,
	"phpsab.docker.dockerContainer": "phpcs-test-apache-1",
	"phpsab.docker.dockerWorkspaceRoot": "/var/www/html",
	"phpsab.docker.dockerExecutablePathCBF": "/usr/bin/phpcbf",
	"phpsab.docker.dockerExecutablePathCS": "/usr/bin/phpcs",
	"phpsab.docker.debug": true,
	"phpsab.docker.snifferMode": "onType",
	"[php]": {
	"editor.defaultFormatter": "mtbdata.vscode-phpsab-docker"
	}
}
```

To get the global paths I needed to run this in the container:

    which phpcs

Have you confirmed phpcs and phpcbf is at `/usr/local/bin` in the container?

Cheers

**Comment by mtbdata711** [comment]
Hey @cballenar,

Ignore the above, managed to re-create the same configuration locally - I think - and put in a fix. There was a conflict going on in the `validate` method of the `Configuration` class.

I'll put up a test branch tomorrow if you are willing to wait until then and give that a go? 

Cheers

**Comment by cballenar** [comment]
Thanks @mtbdata711 ! I was just about to send some additional notes 😄 

That'll be great!  Thanks so much for looking into this so quickly.

**Comment by mtbdata711** [comment]
Hey @cballenar,

I've put up a test branch with a fix here: https://github.com/mtbdata711/vscode-phpsab-docker/tree/mtbdata711/hot-fix/allow-global-phpcs 

Let me know if you are able to pull it down and see if it resolves the issue.

Cheers

**Comment by cballenar** [comment]
@mtbdata711 Thanks! The update worked great. both CS and CBF working as expected 🎉

**Comment by mtbdata711** [comment]
Hey @cballenar,

Sorry - I was at a conference yesterday so slightly behind schedule!

New version - 0.0.10 - has now been released.

Let me know if it solves the issue for you!

Cheers

**Comment by cballenar** [comment]
No prob at all! I really appreciate the work. Works like a charm 😎
