### ISSUE TITLE
Feature: Add setting for reported problems level

### ISSUE THREAD

**Issue by vitkutny** [mtbdata711/vscode-phpsab-docker#18]
Right now its reporting as "error" – same as used for syntax errors, but its only code style. Please add setting for problem level: "error", "warning", "info". And maybe consider changing default value to "warning".

**Comment by mtbdata711** [comment]
Hey @vitkutny,

Sorry for the delay on this, I've been busy with work.

Could you make this request to the main [vscode-phpsab](https://github.com/valeryan/vscode-phpsab) project that this is based on and we will merge it in downstream?

Cheers
